# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'homerwork-3-ErtasBurak' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 7.3.1'

  # Pods for homerwork-3-ErtasBurak

end
